version: '3.4'

networks:
  giveway-network:
    driver: bridge

services:

  webmssql:
    #image: mcr.microsoft.com/mssql/server:latest # if working on Windows
    image: mcr.microsoft.com/azure-sql-edge:latest # if working on MAC arm64
    user: root
    environment:
      - SA_PASSWORD=sa_password_123
      - ACCEPT_EULA=Y
    container_name: giveaway-web-mssql
    ports:
      - 1435:1433
    networks:
      - giveway-network
    volumes:
      - webdbdata:/var/opt/mssql/data

  webapi:
    image: giveaway-webapi
    build:
      context: ./Server
      dockerfile: Web/WebApi/Dockerfile
    container_name: giveaway-webapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_WEBAPI_URLS}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING_WEBDB}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    ports:
      - 81:81
    networks:
      - giveway-network

  webui:
    image: giveaway-webui
    build:
      context: ./Ui
      dockerfile: ./Dockerfile
    container_name: giveaway-webui
    restart: on-failure
    ports:
      - 3000:3000
    environment:
      - BASE_URL=${BASE_URL}
      - AUTH0_SECRET=${AUTH0_SECRET}
      - AUTH0_BASE_URL=${AUTH0_BASE_URL}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_SCOPE=${AUTH0_SCOPE}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - NEXT_BACKEND_URL_SERVER=${NEXT_BACKEND_URL_SERVER}
      - NEXT_PUBLIC_BACKEND_URL_CLIENT=${NEXT_PUBLIC_BACKEND_URL_CLIENT}
      - NEXT_PUBLIC_CDN_IMAGES_BASE_URL=${NEXT_PUBLIC_CDN_IMAGES_BASE_URL}
      - NEXT_PUBLIC_CDN_ACCESS_TOKEN=${NEXT_PUBLIC_CDN_ACCESS_TOKEN}
    networks:
      - giveway-network
    depends_on:
      - webapi
    volumes:
      - ./Ui:/app
      - node_modules:/app/node_modules
      - /app/.next

  chatmongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=GiveawayChat
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
    container_name: giveaway-chat-mongo
    ports:
      - 49155:27017
    networks:
      - giveway-network
    volumes:
      - chatdbdata:/data/db
      
  chatapi:
    image: giveaway-chatapi
    build:
      context: ./Server
      dockerfile: Chat/ChatApi/Dockerfile
    container_name: giveaway-chatapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_CHATAPI_URLS}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING_CHATDB}
    ports:
      - 85:85
    networks:
      - giveway-network

  nginx:
    image: giveaway-nginx
    build:
      context: .
      dockerfile: Nginx/Dockerfile
    ports:
      - 80:80
    container_name: giveaway-nginx
    networks:
      - giveway-network
    depends_on:
      - webapi
      - webui
      - chatapi

volumes:
  webdbdata:
    name: giveaway-web-mssql
  chatdbdata:
    name: giveaway-web-mssql
  node_modules:
    name: nextjs-node-modules
